version = require '..' .VERSION
console.log """
// Generated by LiveScript #version

// LiveScript #version
// Copyright (c) Jeremy Ashkenas, Satoshi Murakami, George Zahariev
// Released under the MIT License
// raw.github.com/gkz/LiveScript/master/LICENSE
"""
